# Image Summarizer Configuration
# Supports multiple AI providers: Amazon Bedrock, Azure OpenAI, OpenAI, LLaVA, Falcon

# Default provider to use (bedrock, azure_openai, openai, llava, falcon)
default_provider: "llava"

# Workflow settings
workflow:
  batch_size: 3
  max_concurrent_requests: 2
  timeout_seconds: 120
  retry_attempts: 3

# Amazon Bedrock Configuration
bedrock:
  # AWS Configuration
  aws_region: "us-east-1"  # Set your preferred region
  aws_access_key_id: "${AWS_ACCESS_KEY_ID}"  # Set via environment variable
  aws_secret_access_key: "${AWS_SECRET_ACCESS_KEY}"  # Set via environment variable
  
  # Image Description Model
  image_model:
    model_id: "anthropic.claude-3-sonnet-20240229-v1:0"
    max_tokens: 1000
    temperature: 0.7
    system_prompt: |
      You are an expert image analyst. Describe the image in detail, focusing on:
      - Main subjects and objects
      - Scene composition and setting
      - Colors, lighting, and mood
      - Any text or notable details
      Keep your description clear and comprehensive.
  
  # Text Summarization Model  
  text_model:
    model_id: "anthropic.claude-3-haiku-20240307-v1:0"
    max_tokens: 500
    temperature: 0.3
    system_prompt: |
      You are a skilled summarizer. Create a concise summary that:
      - Captures the key themes and patterns
      - Highlights the most important elements
      - Maintains clarity and readability
      - Provides meaningful insights about the collection

# Azure OpenAI Configuration
azure_openai:
  # Azure Configuration
  endpoint: "${AZURE_OPENAI_ENDPOINT}"  # Set via environment variable
  api_key: "${AZURE_OPENAI_API_KEY}"    # Set via environment variable
  api_version: "2024-02-15-preview"
  
  # Image Description Model
  image_model:
    deployment_name: "gpt-4o"  # Your Azure deployment name
    max_tokens: 1000
    temperature: 0.7
    system_prompt: |
      You are an expert image analyst. Describe the image in detail, focusing on:
      - Main subjects and objects
      - Scene composition and setting  
      - Colors, lighting, and mood
      - Any text or notable details
      Keep your description clear and comprehensive.
  
  # Text Summarization Model
  text_model:
    deployment_name: "gpt-4o-mini"  # Your Azure deployment name
    max_tokens: 500
    temperature: 0.3
    system_prompt: |
      You are a skilled summarizer. Create a concise summary that:
      - Captures the key themes and patterns
      - Highlights the most important elements
      - Maintains clarity and readability
      - Provides meaningful insights about the collection

# OpenAI Configuration (for comparison)
openai:
  api_key: "${OPENAI_API_KEY}"  # Set via environment variable
  
  # Image Description Model
  image_model:
    model_name: "gpt-4o"
    max_tokens: 1000
    temperature: 0.7
    system_prompt: |
      You are an expert image analyst. Describe the image in detail, focusing on:
      - Main subjects and objects
      - Scene composition and setting
      - Colors, lighting, and mood
      - Any text or notable details
      Keep your description clear and comprehensive.
  
  # Text Summarization Model
  text_model:
    model_name: "gpt-4o-mini"
    max_tokens: 500
    temperature: 0.3
    system_prompt: |
      You are a skilled summarizer. Create a concise summary that:
      - Captures the key themes and patterns
      - Highlights the most important elements
      - Maintains clarity and readability
      - Provides meaningful insights about the collection

# LLaVA Configuration (Local Hugging Face Model)
llava:
  # Model Configuration
  model_id: "llava-hf/llava-v1.6-mistral-7b-hf"
  device: "auto"  # auto, cpu, cuda
  load_in_4bit: true
  temperature: 0.8
  
  # Image Description Model
  image_model:
    model_name: "llava-hf/llava-v1.6-mistral-7b-hf"
    max_tokens: 1000
    temperature: 0.8
    system_prompt: |
      You are an expert image analyst. Describe the image in detail, focusing on:
      - Main subjects and objects
      - Scene composition and setting
      - Colors, lighting, and mood
      - Any text or notable details
      Keep your description clear and comprehensive.
  
  # Text Summarization Model (uses LLaVA itself for text tasks)
  text_model:
    model_name: "llava-hf/llava-v1.6-mistral-7b-hf"  # Same as image model - LLaVA can do both
    max_tokens: 500
    temperature: 0.3
    system_prompt: |
      You are a skilled summarizer. Create a concise summary that:
      - Captures the key themes and patterns
      - Highlights the most important elements
      - Maintains clarity and readability
      - Provides meaningful insights about the collection

# Falcon AI Configuration (Local Hugging Face Models)
falcon:
  # Model Configuration
  device: "auto"  # auto, cpu, cuda
  
  # Image Description Model (uses BLIP for image captioning)
  image_model:
    model_name: "Salesforce/blip-image-captioning-base"
    max_tokens: 1000
    temperature: 0.7
    system_prompt: |
      You are an expert image analyst. Describe the image in detail, focusing on:
      - Main subjects and objects
      - Scene composition and setting
      - Colors, lighting, and mood
      - Any text or notable details
      Keep your description clear and comprehensive.
  
  # Text Summarization Model (uses Falconsai/text_summarization)
  text_model:
    model_name: "Falconsai/text_summarization"
    max_tokens: 500
    temperature: 0.3
    system_prompt: |
      You are a skilled summarizer. Create a concise summary that:
      - Captures the key themes and patterns
      - Highlights the most important elements
      - Maintains clarity and readability
      - Provides meaningful insights about the collection

# Output settings
output:
  save_individual_descriptions: true
  save_final_summary: true
  output_format: "json"  # json, yaml, or txt
  include_metadata: true

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/image_summarizer.log"